services:
  bot:
    image: ghcr.io/cornstalk24/shorturl-tgbot:latest
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      TZ: "${TZ}"
      BOT_TOKEN: "${BOT_TOKEN}"
      PYTHONPATH: "${PYTHONPATH}"
    env_file:
      - .env
    volumes:
      - ./data:/app/data
    restart: unless-stopped
