services:
  shorturl-bot:
    image: ghcr.io/cornstalk24/shorturl-tgbot:latest
    environment:
      TZ: "${TZ}"
      BOT_TOKEN: "${BOT_TOKEN}"
      PYTHONPATH: "${PYTHONPATH}"
    volumes:
      - ./data:/app/data
    restart: unless-stopped
