name: Deploy to Docker Hub (or GitHub Container Registry)

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: ghcr.io/cornstalk24/shorturl-tgbot:latest

      - name: Deploy Docker container
        run: |
          docker run -d --name shorturl-tgbot ghcr.io/cornstalk24/shorturl-tgbot:latest
